Shop:
  Path: /ManageShop/
  Weight: 90
  Children:
    Products/Parts:
      Path: /Manage/ViewData/Part
      Weight: 1
    Products/Parts sets:
      Path: /Manage/ViewData/Sets/
      Weight: 2
    Import product feed:
      Path: /ManageShop/ImportProductFeed/
      Weight: 999

